version: '3'

services:

  todoback:
    ports:
      - 3001:3001
    image: todobackend

  todofront:
    ports:
      - 3000:3000
    image: todofrontend
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback

  todotests:
    depends_on:
      - todofront
      - todoback
    image: todotests
    environment:
      - FRONT_HOST=todofront

